### ISSUE TITLE
Commande KO avec livraison gratuite / order KO with free shipping

### ISSUE THREAD

**Issue by Crouvizier** [hipay/hipay-enterprise-sdk-prestashop#85]
### FR

Bonjour,

Je crée cette issue car nous rencontrons un problème sur notre boutique lié à la création de certaines commandes :

Contexte :
Pour certaines commandes, nous créons la commande dans le back-office en cochant l'option de livraison gratuite. Ensuite, lorsque nous passons à la validation de la commande (via le front-end ou la méthode MoTo), la commande est annulée en raison d'une erreur, comme le montre la capture d'écran ci-jointe.

![Screenshot_324](https://github.com/hipay/hipay-enterprise-sdk-prestashop/assets/87063808/4e5242fc-a4cd-4993-87de-d2dfc7e8c692)
![Screenshot_325](https://github.com/hipay/hipay-enterprise-sdk-prestashop/assets/87063808/d68a0800-9b77-465f-9ccd-efb34b05b5fc)
![Screenshot_326](https://github.com/hipay/hipay-enterprise-sdk-prestashop/assets/87063808/f3a33fa0-5694-416b-933c-c54ea2effe33)

Reproduction :

1. Créer une commande depuis le back-office.
2. Sélectionner un client, un ou plusieurs produits, et une adresse de livraison/facturation.
3. Choisir un mode de livraison.
4. Cocher l'option "Livraison gratuite".
5. Dans le Back-Office :
    a: Créer la commande avec le statut "En attente de paiement MO/TO (HiPay)".
    b: Valider la commande avec un moyen de paiement valide (ou un moyen de test si la boutique est en mode test).
5. Dans le Front-End :
    a: Choisir le mode de paiement par carte bancaire (HiPay).
    b: Remplir les champs avec un moyen de paiement valide (ou un moyen de test si la boutique est en mode test) et valider la commande.
6. La commande échoue.

Voici les erreurs que nous trouvons dans les logs du module :

> 2023/12/07 - 15:23:32: HipayLogs:logException:Invalid format basket
> 2023/12/07 - 15:23:32: HipayLogs:logException:#0 /public_html/modules/hipay_enterprise/lib/vendor/hipay/hipay-fullservice-sdk-php/lib/HiPay/Fullservice/HTTP/ClientProvider.php(93): HiPay\Fullservice\HTTP\SimpleHTTPClient->doRequest('POST', 'v1/order', Array, false, false)
> #1 /public_html/modules/hipay_enterprise/lib/vendor/hipay/hipay-fullservice-sdk-php/lib/HiPay/Fullservice/Gateway/Client/GatewayClient.php(147): HiPay\Fullservice\HTTP\ClientProvider->request('POST', 'v1/order', Array)
> #2 /public_html/modules/hipay_enterprise/classes/apiCaller/ApiCaller.php(141): HiPay\Fullservice\Gateway\Client\GatewayClient->requestNewOrder(Object(HiPay\Fullservice\Gateway\Request\Order\OrderRequest))
> #3 /public_html/modules/hipay_enterprise/classes/apiHandler/ApiHandler.php(429): ApiCaller::requestDirectPost(Object(Hipay_enterprise), Array)
> #4 /public_html/modules/hipay_enterprise/classes/apiHandler/ApiHandler.php(108): Apihandler->handleDirectOrder(Array)
> #5 /public_html/modules/hipay_enterprise/controllers/front/redirect.php(310): Apihandler->handleCreditCard('direct_post', Array)
> #6 /public_html/modules/hipay_enterprise/controllers/front/redirect.php(127): Hipay_enterpriseRedirectModuleFrontController->apiNewCC(Object(Cart), Object(Context), Object(Customer), false, false)
> #7 /public_html/classes/controller/Controller.php(295): Hipay_enterpriseRedirectModuleFrontController->postProcess()
> #8 /public_html/classes/Dispatcher.php(525): ControllerCore->run()
> #9 /public_html/index.php(28): DispatcherCore->dispatch()
> #10 {main}
![Screenshot_327](https://github.com/hipay/hipay-enterprise-sdk-prestashop/assets/87063808/19842527-1b10-450d-adf6-a9c8881fa37f)

En activant le mode débug, nous obtenons un peu plus d'informations sur l'origine du problème :

> 2023/12/07 - 15:41:38: HipayLogs:logException:Warning: Division by zero
> 2023/12/07 - 15:41:38: HipayLogs:logException:#0 /public_html/modules/hipay_enterprise/classes/apiFormatter/Cart/CartFormatter.php(76): CartFormatter->getFeesItem(Array)
> #1 /public_html/modules/hipay_enterprise/classes/apiFormatter/Cart/CartFormatter.php(43): CartFormatter->mapRequest(Object(HiPay\Fullservice\Gateway\Model\Cart\Cart))
> #2 /public_html/modules/hipay_enterprise/classes/apiHandler/ApiHandler.php(360): CartFormatter->generate()
> #3 /public_html/modules/hipay_enterprise/classes/apiHandler/ApiHandler.php(339): Apihandler->getCart(Object(CartFormatter))
> #4 /public_html/modules/hipay_enterprise/classes/apiHandler/ApiHandler.php(96): Apihandler->baseParamsInit(Array)
> #5 /public_html/modules/hipay_enterprise/controllers/front/redirect.php(310): Apihandler->handleCreditCard('direct_post', Array)
> #6 /public_html/modules/hipay_enterprise/controllers/front/redirect.php(127): Hipay_enterpriseRedirectModuleFrontController->apiNewCC(Object(Cart), Object(Context), Object(Customer), false, false)
> #7 /public_html/classes/controller/Controller.php(295): Hipay_enterpriseRedirectModuleFrontController->postProcess()
> #8 /public_html/classes/Dispatcher.php(525): ControllerCore->run()
> #9 /public_html/index.php(28): DispatcherCore->dispatch()
> #10 {main}
![Screenshot_328](https://github.com/hipay/hipay-enterprise-sdk-prestashop/assets/87063808/8900be80-2a8d-4f77-a482-dfcf0faa07a1)

Informations sur l'environnement :

Version du module : v2.20.0
Version de PrestaShop : 1.7.8.10
Version PHP : 7.4.33

---

### EN

Hello,

I am creating this issue because we are experiencing a problem on our shop related to the creation of certain orders:

Context:
For some orders, we create the order in the back-office by checking the option for free shipping. Then, when we proceed to validate the order (via the front-end or the MoTo method), the order gets canceled due to an error, as shown in the attached screenshot.

Reproduction:

1. Create an order from the back-office.
2. Select a customer, one or more products, and a delivery/billing address.
3. Choose a shipping method.
4. Check the "Free Shipping" option.
5. In the Back-Office:
   a. Create the order with the status "Awaiting MO/TO Payment (HiPay)."
   b. Validate the order with a valid payment method (or a test method if the shop is in test mode).
5. In the Front-End:
   a. Choose the payment method by credit card (HiPay).
   b. Fill in the fields with a valid payment method (or a test method if the shop is in test mode) and validate the order.
6. => The order fails.

Here are the errors we find in the module's logs:

> 2023/12/07 - 15:23:32: HipayLogs:logException:Invalid format basket
> 2023/12/07 - 15:23:32: HipayLogs:logException:#0 /public_html/modules/hipay_enterprise/lib/vendor/hipay/hipay-fullservice-sdk-php/lib/HiPay/Fullservice/HTTP/ClientProvider.php(93): HiPay\Fullservice\HTTP\SimpleHTTPClient->doRequest('POST', 'v1/order', Array, false, false)
> #1 /public_html/modules/hipay_enterprise/lib/vendor/hipay/hipay-fullservice-sdk-php/lib/HiPay/Fullservice/Gateway/Client/GatewayClient.php(147): HiPay\Fullservice\HTTP\ClientProvider->request('POST', 'v1/order', Array)
> #2 /public_html/modules/hipay_enterprise/classes/apiCaller/ApiCaller.php(141): HiPay\Fullservice\Gateway\Client\GatewayClient->requestNewOrder(Object(HiPay\Fullservice\Gateway\Request\Order\OrderRequest))
> #3 /public_html/modules/hipay_enterprise/classes/apiHandler/ApiHandler.php(429): ApiCaller::requestDirectPost(Object(Hipay_enterprise), Array)
> #4 /public_html/modules/hipay_enterprise/classes/apiHandler/ApiHandler.php(108): Apihandler->handleDirectOrder(Array)
> #5 /public_html/modules/hipay_enterprise/controllers/front/redirect.php(310): Apihandler->handleCreditCard('direct_post', Array)
> #6 /public_html/modules/hipay_enterprise/controllers/front/redirect.php(127): Hipay_enterpriseRedirectModuleFrontController->apiNewCC(Object(Cart), Object(Context), Object(Customer), false, false)
> #7 /public_html/classes/controller/Controller.php(295): Hipay_enterpriseRedirectModuleFrontController->postProcess()
> #8 /public_html/classes/Dispatcher.php(525): ControllerCore->run()
> #9 /public_html/index.php(28): DispatcherCore->dispatch()
> #10 {main}

When enabling debug mode, we get more information about the origin of the problem:

> 2023/12/07 - 15:41:38: HipayLogs:logException:Warning: Division by zero
> 2023/12/07 - 15:41:38: HipayLogs:logException:#0 /public_html/modules/hipay_enterprise/classes/apiFormatter/Cart/CartFormatter.php(76): CartFormatter->getFeesItem(Array)
> #1 /public_html/modules/hipay_enterprise/classes/apiFormatter/Cart/CartFormatter.php(43): CartFormatter->mapRequest(Object(HiPay\Fullservice\Gateway\Model\Cart\Cart))
> #2 /public_html/modules/hipay_enterprise/classes/apiHandler/ApiHandler.php(360): CartFormatter->generate()
> #3 /public_html/modules/hipay_enterprise/classes/apiHandler/ApiHandler.php(339): Apihandler->getCart(Object(CartFormatter))
> #4 /public_html/modules/hipay_enterprise/classes/apiHandler/ApiHandler.php(96): Apihandler->baseParamsInit(Array)
> #5 /public_html/modules/hipay_enterprise/controllers/front/redirect.php(310): Apihandler->handleCreditCard('direct_post', Array)
> #6 /public_html/modules/hipay_enterprise/controllers/front/redirect.php(127): Hipay_enterpriseRedirectModuleFrontController->apiNewCC(Object(Cart), Object(Context), Object(Customer), false, false)
> #7 /public_html/classes/controller/Controller.php(295): Hipay_enterpriseRedirectModuleFrontController->postProcess()
> #8 /public_html/classes/Dispatcher.php(525): ControllerCore->run()
> #9 /public_html/index.php(28): DispatcherCore->dispatch()
> #10 {main}

Environment Information:

Module Version: v2.20.0
PrestaShop Version: 1.7.8.10
PHP Version: 7.4.33

**Comment by Crouvizier** [comment]
c'est avec plaisir :)

**Comment by stormwind85** [comment]
Corrigé lors de la release [2.21.3](https://github.com/hipay/hipay-enterprise-sdk-prestashop/releases/tag/2.21.3)
